### ISSUE TITLE
Add retry to external submission downloads

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#112]
Modify  ExternalDataSubmissionTask._download_remote_challenge_data_package() to retry download if an exception is encountered (with user configurable retry an sleep times). Reason for this is a network hiccup caused the download to fail even though the data on remote server was good.

Error
------------
2017-01-17 15:01:35,651 DEBUG d3r.celpp.task Creating directory: /data/celpp/201
7/dataset.week.3/stage.6.33567_2.extsubmission
2017-01-17 15:01:35,696 DEBUG d3r.celpp.filetransfer Connecting to ftp.box.com w
ith user churas.camera@gmail.com
2017-01-17 15:01:37,472 DEBUG d3r.celpp.filetransfer Downloading file : /celppweekly/usersubmissions/33567_2/celpp_week3_2017_dockedresults_33567_2.tar.gz to /data/celpp/2017/dataset.week.3/stage.6.33567_2.extsubmission/celpp_week3_2017_dockedresults_33567_2.tar.gz
2017-01-17 15:02:39,574 ERROR d3r.celpp.filetransfer Caught exception downloading file/celppweekly/usersubmissions/33567_2/celpp_week3_2017_dockedresults_33567_2.tar.gz to /data/celpp/2017/dataset.week.3/stage.6.33567_2.extsubmission/celpp_week3_2017_dockedresults_33567_2.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/celpp/filetransfer.py", line 389, in download_file
    self._ftp.get(remote_path, local=local_path)
  File "/usr/lib/python2.6/site-packages/ftpretty.py", line 70, in get
    self.conn.retrbinary("RETR %s" % remote, local_file.write)
  File "/usr/lib64/python2.6/ftplib.py", line 405, in retrbinary
    data = conn.recv(blocksize)
timeout: timed out
2017-01-17 15:02:39,610 DEBUG d3r.celpp.filetransfer Download operation took 62 seconds
2017-01-17 15:02:39,610 DEBUG d3r.celpp.filetransfer Attempting to close ftp connection
2017-01-17 15:02:42,529 ERROR d3r.celpp.extsubmission Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/celpp/extsubmission.py", line 312, in run
    self._runtask()
  File "/usr/lib/python2.6/site-packages/d3r/celpp/extsubmission.py", line 291, in _runtask
    self._move_challenge_data_package_into_task_dir(chall_name)
  File "/usr/lib/python2.6/site-packages/d3r/celpp/extsubmission.py", line 252, in _move_challenge_data_package_into_task_dir
    for entry in os.listdir(package_dir):
OSError: [Errno 2] No such file or directory: '/data/celpp/2017/dataset.week.3/stage.6.33567_2.extsubmission/celpp_week3_2017_dockedresults_33567_2'
2017-01-17 15:02:42,533 INFO d3r.celpp.task stage.6.33567_2.extsubmission task took 67 seconds and has finished with status start
2017-01-17 15:02:42,533 ERROR d3r.celpp.task /data/celpp/2017/dataset.week.3/stage.6.33567_2.extsubmission task failed with error Caught exception [Errno 2] No such file or directory: '/data/celpp/2017/dataset.week.3/stage.6.33567_2.extsubmission/celpp_week3_2017_dockedresults_33567_2'

**Comment by coleslaw481** [comment]
Fixed aim to release in 1.6.6
