### ISSUE TITLE
evaluation failed on autodock vina 

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#131]
On version 1.7.1 of d3r:
evaluation raised a KeyError and exited. See output below:

Running command: evaluate.py --pdbdb /data/pdb.extracted --dockdir /data/celpp/2017/dataset.week.13/stage.6.autodockvina --outdir /data/celpp/2017/dataset.week.13/stage.7.autodockvina.evaluation
Although considered non fatal for processing of stage a non zero exit code: 1received. Standard out:  Standard error : Traceback (most recent call last):
  File "/usr/bin/evaluate.py", line 550, in <module>
    pickle_result = main_score(dockDir, pdbloc, evaluateDir, )
  File "/usr/bin/evaluate.py", line 515, in main_score
    score_dic[target_name][docked_structure_type] = min(score_dic[target_name][docked_structure_type])
KeyError: 'hiTanimoto'

**Comment by j-wags** [comment]
Week 12 probably failed because of a programmed evaluation timeout, because I didn't apply the exclude-proteins-over-750-AA patch to the 33567.autodockvina contestant that I run. 

Week 13 failed because of a really bizarre candidate structure, 3fw3, which begins with residues numbering 5, 6, 7, 8, 9, 10, 11, 11A, 11B, 11C, 11D, 11G, 11H, 12, 13... 
I have no idea why this is. The right thing to do here is probably to have a try/except in evaluation to catch failures like this. I'll work on implementing it this week.

**Comment by j-wags** [comment]
Week 14 failed because autodocktools' prepare_ligand4.py choked on the osmium in the 5v4i ligand. 

Because of the diversity of problems we see with this common set of tools, and given that we are beginning to receive external submissions, I think it's time to implement try/except logic in evaluation.

**Comment by coleslaw481** [comment]
This code has been rewritten, so Jeff will test again to see if this has been resolved
