### ISSUE TITLE
Investigate why 2017 dataset.week.52 evaluation task failed.

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#173]
For this week it looks like evaluation ran, but exited with non zero exit code. celpprunner.py seeing the error then exited without running postevaluation as its supposed to do. 

Entries from celpprunner.log
```Bash
2017-12-27 23:23:17,258 DEBUG d3r.celpprunner Task 33678_4.extsubmission.evaluat
ion has finished running  with status complete
2017-12-27 23:23:17,258 ERROR d3r.celpprunner Non zero exit code from task evalu
ationexiting
2017-12-27 23:23:17,258 DEBUG d3r.celpprunner Releasing lock
```

Not sure if its related, but this error was found earlier in the log:

```Bash
017-12-27 05:43:49,252 DEBUG d3r.celpp.util Waiting for process to complete
2017-12-27 05:43:49,253 DEBUG d3r.celpp.util Polling returned None, looping until p.returncode is not None
2017-12-27 17:43:50,944 INFO d3r.celpp.util Timeout of 43200exceeded invoking terminate
2017-12-27 17:43:51,960 DEBUG d3r.celpp.util Got a return code that is not None: -15
2017-12-27 17:43:51,961 DEBUG d3r.celpp.util Writing stderr and stdout to /celpp/data/2017/dataset.week.52/stage.7.33567_oefred-smallbox.extsubmission.evaluation/evaluate.pyf7c9b47c-eb0b-11e7-
8133-0050568e0663.tmpdir
2017-12-27 17:43:52,012 ERROR d3r.celpprunner Error caught exception
Traceback (most recent call last):
  File "/usr/bin/celpprunner.py", line 182, in run_tasks
    task.run()
  File "/usr/lib/python2.7/site-packages/d3r/celpp/evaluation.py", line 653, in run
    kill_delay=killdelay)
  File "/usr/lib/python2.7/site-packages/d3r/celpp/task.py", line 705, in run_external_command
    shutil.rmtree(cmd_tmp_dir)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/celpp/data/2017/dataset.week.52/stage.7.33567_oefred-smallbox.extsubmission.evaluation/evaluate.pyf7c9b47c-eb0b-11e7-8133-0050568e0663.tmpdir'
2017-12-27 17:43:52,393 DEBUG d3r.celpprunner Task 33567_oefred-smallbox.extsubmission.evaluation has finished running  with status start
2017-12-27 17:43:52,393 ERROR d3r.celpprunner Error running task 33567_oefred-smallbox.extsubmission.evaluation Caught Exception running task: 
```

**Comment by crawld** [comment]
These timeouts during evaluation are occurring more frequently. Increase the timeout values?

Also, the above exception seems to occur when calling shutil.rmtree() on the temporary directory - probably due to the evaluation process still writing in there. This can probably fixed by setting ignore_errors=True for rmtree().
