### ISSUE TITLE
unit tests on molefilevalidator.py failing

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#177]
When openeye is available and licensed the following two unit tests fail:

```Bash
======================================================================
ERROR: test_validate_molfiles_in_tarball_real (tests.test_molfilevalidator.TestMolFileValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/churas/src/D3R/tests/test_molfilevalidator.py", line 671, in test_validate_molfiles_in_tarball_real
    moldb)
  File "/Users/churas/src/D3R/d3r/molfilevalidator.py", line 634, in _validate_molfiles_in_tarball
    theargs.excludedir):
  File "/Users/churas/src/D3R/d3r/molfilevalidator.py", line 561, in _molfile_from_tarfile_generator
    temp_dir = tempfile.mkdtemp(dir=tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: 'SuppInfo/tmpjpPQVW'

======================================================================
ERROR: test_validate_molfiles_in_tarball_real_with_skiplist (tests.test_molfilevalidator.TestMolFileValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/churas/src/D3R/tests/test_molfilevalidator.py", line 706, in test_validate_molfiles_in_tarball_real_with_skiplist
    moldb)
  File "/Users/churas/src/D3R/d3r/molfilevalidator.py", line 634, in _validate_molfiles_in_tarball
    theargs.excludedir):
  File "/Users/churas/src/D3R/d3r/molfilevalidator.py", line 561, in _molfile_from_tarfile_generator
    temp_dir = tempfile.mkdtemp(dir=tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: 'SuppInfo/tmpWnHhX8'

----------------------------------------------------------------------
Ran 487 tests in 29.940s

FAILED (errors=2)
make: *** [test] Error 1
```

**Comment by coleslaw481** [comment]
Verified tests pass on chrisdev branch
