### ISSUE TITLE
uncaught exception when trying to download external submissions

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#181]
Evaluation failed for dataset.week.14 cause celpp was unable to download external submissions. 

Need to better handle this error and add retry

Output from log file:
```Bash
2018-04-03 15:01:01,452 INFO d3r.celpprunner Starting extsubmission stage
2018-04-03 15:01:01,452 DEBUG d3r.celpprunner Looking for lock file: /celpp/data/2018/dataset.week.14/celpprunner.extsubmission.lockpid
2018-04-03 15:01:01,458 INFO d3r.celpprunner Acquiring lock
2018-04-03 15:01:01,491 DEBUG d3r.celpprunner Getting task list for extsubmission
2018-04-03 15:01:01,491 DEBUG d3r.celpp.task ftpconfig set to /home/d3r/box.config
2018-04-03 15:01:01,492 DEBUG d3r.celpp.task ftpconfig set to /home/d3r/box.config
2018-04-03 15:01:01,492 DEBUG d3r.celpp.task ftpconfig set to /home/d3r/box.config
2018-04-03 15:01:01,492 DEBUG d3r.celpp.task ftpconfig set to /home/d3r/box.config
2018-04-03 15:01:01,492 DEBUG d3r.celpp.filetransfer Connecting to ftp.box.com with user churas.camera@gmail.com
2018-04-03 15:01:02,864 DEBUG d3r.celpp.filetransfer Deleting file : /celppweekly/challengedata/latest.txt
2018-04-03 15:01:04,752 DEBUG d3r.celpp.filetransfer  Delete operation returned: True
2018-04-03 15:01:04,752 DEBUG d3r.celpp.filetransfer Delete operation took 2 seconds
2018-04-03 15:01:04,752 DEBUG d3r.celpp.filetransfer Examining : /celppweekly/usersubmissions
2018-04-03 15:01:04,762 ERROR d3r.celpp.filetransfer Caught exception examining /celppweekly/usersubmissions
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/d3r/celpp/filetransfer.py", line 425, in list_dirs
    for paths in self._ftp.list(remote_dir, extra=True):
  File "/usr/lib/python2.7/site-packages/ftpretty.py", line 158, in list
    self.conn.dir(remote, self._collector)
  File "/usr/lib64/python2.7/ftplib.py", line 534, in dir
    self.retrlines(cmd, func)
  File "/usr/lib64/python2.7/ftplib.py", line 437, in retrlines
    conn = self.transfercmd(cmd)
  File "/usr/lib64/python2.7/ftplib.py", line 376, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib64/python2.7/ftplib.py", line 335, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2018-04-03 15:01:05,020 DEBUG d3r.celpp.filetransfer list directory operation took 1 seconds
2018-04-03 15:01:05,021 DEBUG d3r.celpp.filetransfer Attempting to close ftp connection
2018-04-03 15:01:05,024 DEBUG d3r.celpprunner Releasing lock
2018-04-03 15:01:05,025 ERROR d3r.celpprunner Error caught exception
Traceback (most recent call last):
  File "/usr/bin/celpprunner.py", line 745, in main
    return run_stages(theargs)
  File "/usr/bin/celpprunner.py", line 150, in run_stages
    task_list = get_task_list_for_stage(updatedtheargs, stage_name)
  File "/usr/bin/celpprunner.py", line 301, in get_task_list_for_stage
    'uh oh no tasks for ' + stage_name + ' stage')
```

**Comment by coleslaw481** [comment]
Add retry count and timeout to filetransfer.py FtpFileTransfer.list_dirs which requires adding it to the parent object.

**Comment by coleslaw481** [comment]
added retry count and timeout to list_dirs. This parameters can be set via --extsleep and --extretry from celpprunner.py

**Comment by crawld** [comment]
A submission in 2019 week 8 was not downloaded due to the same exception in list_files.
