### ISSUE TITLE
proteinligprep run failed 2016/dataset.week.2

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#3]
Please look at nif1 to examine input files.  Below is the error from the proteinligprep.py script from version 0.8.4 of celpprunner:

Traceback (most recent call last):
  File "/usr/bin/proteinligprep.py", line 268, in <module>
    main_proteinprep(stage_2_result, pdb_location, stage_3_result)
  File "/usr/bin/proteinligprep.py", line 165, in main_proteinprep
    ligand_center = get_center ("largest.pdb", largest_ligand) 
  File "/usr/bin/proteinligprep.py", line 64, in get_center
    x += float(xyz_line[30:38])
ValueError: invalid literal for float(): NDS TO I

**Comment by coleslaw481** [comment]
Has this been resolved?

**Comment by shuail** [comment]
This bug has been fixed.
