### ISSUE TITLE
challenge data failed with error

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#60]
Challenge data task failed with this message in error file:

Caught exception Unable to upload /data/celpp/2016/dataset.week.29/stage.4.challengedata/celpp_week29_2016.tar.gz to /celppweekly/challengedata/celpp_week29_2016.tar.gz : 'NoneType' object has no attribute 'put'

celpprunner.log of failure:

2016-07-16 06:02:09,973 DEBUG d3r.celpp.filetransfer Direct uploading file: /dat
a/celpp/2016/dataset.week.29/stage.4.challengedata/celpp_week29_2016.tar.gz to /
celppweekly/challengedata/celpp_week29_2016.tar.gz
2016-07-16 06:02:09,973 ERROR d3r.celpp.filetransfer Caught exception direct uploading file/data/celpp/2016/dataset.week.29/stage.4.challengedata/celpp_week29_2016.tar.gz to /celppweekly/challengedata/celpp_week29_2016.tar.gz
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/celpp/filetransfer.py", line 418, in upload_file_direct
    size = self._ftp.put(file, remote_path)
AttributeError: 'NoneType' object has no attribute 'put'
2016-07-16 06:02:09,982 DEBUG d3r.celpp.filetransfer End of direct_file_upload operation took 0 seconds
2016-07-16 06:02:09,982 DEBUG d3r.celpp.filetransfer ftp connection is None, just returning
2016-07-16 06:02:09,983 ERROR d3r.celpp.challengedata Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/celpp/challengedata.py", line 476, in run
    self._upload_challenge_file(tfile)
  File "/usr/lib/python2.6/site-packages/d3r/celpp/challengedata.py", line 381, in _upload_challenge_file
    raise Exception(uploader.get_error_msg())
Exception: Unable to upload /data/celpp/2016/dataset.week.29/stage.4.challengedata/celpp_week29_2016.tar.gz to /celppweekly/challengedata/celpp_week29_2016.tar.gz : 'NoneType' object has no attribute 'put'
2016-07-16 06:02:09,994 INFO d3r.celpp.task stage.4.challengedata task took 141 seconds and has finished with status start

**Comment by coleslaw481** [comment]
Fixed with 1.3.3 release https://github.com/drugdata/D3R/commit/769b2f1b9cb9c45a498cf4a944c591ba4e143f91
