### ISSUE TITLE
celpprunner fails if evaluation is rerun with completed evaluation tasks

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#87]
For example if a stage.6.glide exists and is complete and a stage.7.glide.evaluation exists and is complete then rerunning celpprunner evaluation stage will cause this error:

Traceback (most recent call last):
  File "/Users/churas/src/D3R/tests/celpp/test_evaluation.py", line 227, in test_get_evaluation_tasks_on_with_valid_completed_algo_dir
    task_list = stf.get_evaluation_tasks()
  File "/Users/churas/src/D3R/d3r/celpp/evaluation.py", line 137, in get_evaluation_tasks
    ' added : ' + stask.get_error())
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by coleslaw481** [comment]
Code assumed that if an evaluation task could not run there was an error. This was wrong cause if the evaluation task had already been run then there wouldn't be an error.
Pushed fix to master. 
 17b643a..213ae47  master -> master
