### ISSUE TITLE
Investigate why stage.3.blastnfilter failed on dataset.week.42 on version 1.6.0

### ISSUE THREAD

**Issue by coleslaw481** [drugdata/D3R#89]
blastnfilter failed with a non zero exit code.  In blastnfilter.py.stderr file some exceptions were thrown. Below is edited output from blastnfilter.py.stderr file:

Running command: /usr/bin/blastnfilter.py --nonpolymertsv /data/celpp/2016/dataset.week.42/stage.2.dataimport/new_release_structure_nonpolymer.tsv --sequencetsv /data/celpp/2016/dataset.week.42/stage.2.dataimport/new_release_structure_sequence_canonical.tsv --pdbblastdb /data/celpp/2016/dataset.week.42/stage.1.makeblastdb --compinchi /data/celpp/2016/dataset.week.42/stage.2.dataimport/Components-inchi.ich --crystalpH /data/celpp/2016/dataset.week.42/stage.2.dataimport/new_release_crystallization_pH.tsv --pdbdb /data/pdb.extracted --log DEBUG --outdir /data/celpp/2016/dataset.week.42/stage.3.blastnfilter
Although considered non fatal for processing of stage a non zero exit code: 2received. Standard out: The total number of structures is: 169
The total number of complexes is: 135
The total number of complexes with at least one dockable ligand is: 80
The total number of complexes with only one dockable ligand is: 56
The total number of monomers is: 132
The total number of monomers with one dockable ligand is: 42
The total number of multimers is: 37
The total number of multimers with one dockable ligand is: 14
Please set an rd mol object before calculating num of atoms
Please set an rd mol object before calculating num of heavy atoms
Please set an rd mol object before calculating num of atoms
Please set an rd mol object before calculating num of heavy atoms
Please set an rd mol object before calculating num of atoms
Please set an rd mol object before calculating num of heavy atoms
Please set an rd mol object before calculating num of atoms
Please set an rd mol object before calculating num of heavy atoms
Please set an rd mol object before calculating num of atoms
Please set an rd mol object before calculating num of heavy atoms
Please set an rd mol object before calculating num of atoms
Please set an rd mol object before calculating num of heavy atoms
 Standard error : 2016-10-15 00:02:15,670 DEBUG d3r.blastnfilter Starting run
2016-10-15 00:02:15,670 DEBUG d3r.utilities.run Creating queries
2016-10-15 00:02:15,699 DEBUG d3r.utilities.in_put Found 169 queries from /data/celpp/2016/dataset.week.42/stage.2.dataimport/new_release_structure_sequence_canonical.tsv file
2016-10-15 00:02:15,703 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,756 DEBUG d3r.blast.query In set_ligand()
.
.
.
2016-10-15 00:02:15,845 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,846 ERROR d3r.utilities.in_put Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/utilities/in_put.py", line 95, in read_ligands
    inchi = words[2]
IndexError: list index out of range
2016-10-15 00:02:15,847 ERROR d3r.utilities.in_put Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/utilities/in_put.py", line 95, in read_ligands
    inchi = words[2]
IndexError: list index out of range
2016-10-15 00:02:15,847 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,847 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,914 ERROR d3r.utilities.in_put Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/utilities/in_put.py", line 95, in read_ligands
    inchi = words[2]
IndexError: list index out of range
2016-10-15 00:02:15,915 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,915 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,921 ERROR d3r.utilities.in_put Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/utilities/in_put.py", line 95, in read_ligands
    inchi = words[2]
IndexError: list index out of range
2016-10-15 00:02:15,921 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,921 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,923 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,924 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,924 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,924 ERROR d3r.utilities.in_put Caught exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/utilities/in_put.py", line 95, in read_ligands
    inchi = words[2]
IndexError: list index out of range
2016-10-15 00:02:15,924 DEBUG d3r.blast.query In set_ligand()
.
.
2016-10-15 00:02:15,941 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,941 DEBUG d3r.blast.query In set_ligand()
2016-10-15 00:02:15,942 DEBUG d3r.utilities.analysis Writing summary.txt file to /data/celpp/2016/dataset.week.42/stage.3.blastnfilter
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis INPUT SUMMARY
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   entries:                             169
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   complexes:                           135
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   dockable complexes:                   56
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   monomers:                            132
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   dockable monomers:                    42
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   multimers:                            37
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   dockable multimers:                   14
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis FILTERING CRITERIA
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   No. of query sequences           <=    1
2016-10-15 00:02:15,943 DEBUG d3r.utilities.analysis   No. of dockable ligands           =    1
2016-10-15 00:02:15,944 DEBUG d3r.utilities.analysis   Percent identity                 >=    0.95
2016-10-15 00:02:15,944 DEBUG d3r.utilities.analysis   Percent Coverage                 >=    0.9
2016-10-15 00:02:15,944 DEBUG d3r.utilities.analysis   No. of hit sequences             <=    2
2016-10-15 00:02:15,944 DEBUG d3r.utilities.analysis   Structure determination method:        x-ray diffraction
2016-10-15 00:02:15,944 DEBUG d3r.utilities.analysis
2016-10-15 00:02:15,944 DEBUG d3r.utilities.run # queries 169
2016-10-15 00:02:15,944 DEBUG d3r.utilities.run Blasting query:  1fcz
2016-10-15 00:02:15,944 DEBUG d3r.utilities.run Hit.set_pdb_dir
2016-10-15 00:02:15,944 DEBUG d3r.utilities.run Hit.set_pdb_dict
2016-10-15 00:02:15,944 DEBUG d3r.blast.hit Parsing /data/celpp/2016/dataset.week.42/stage.1.makeblastdb/pdb_seqres.txt
2016-10-15 00:02:51,848 DEBUG d3r.utilities.run Ligand.set_inchi_component
2016-10-15 00:02:51,863 ERROR d3r.blast.ligand Caught exception trying to read /data/celpp/2016/dataset.week.42/stage.2.dataimport/Components-inchi.ich file
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/blast/ligand.py", line 43, in set_inchi_component
    inchi = words[0]
IndexError: list index out of range
2016-10-15 00:02:51,863 ERROR d3r.blast.ligand Caught exception trying to read /data/celpp/2016/dataset.week.42/stage.2.dataimport/Components-inchi.ich file
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/blast/ligand.py", line 44, in set_inchi_component
    resname = words[1]
IndexError: list index out of range
2016-10-15 00:02:51,863 ERROR d3r.blast.ligand Caught exception trying to read /data/celpp/2016/dataset.week.42/stage.2.dataimport/Components-inchi.ich file
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/d3r/blast/ligand.py", line 43, in set_inchi_component
    inchi = words[0]
IndexError: list index out of range
2016-10-15 00:02:51,908 DEBUG d3r.utilities.run query.run_blast
2016-10-15 00:02:51,908 DEBUG d3r.blast.query In run_blast()
2016-10-15 00:02:51,908 DEBUG d3r.blast.query Running blast_monomer

**Comment by shuail** [comment]
This bug is caused by the invalid operation to the top of the holo hit (try to extract the mcss info of the hit while the hit didn't have mcss info). Fix the bug by skipping the invalid holo hit and go to the next one in the holo list.
